spring.datasource.url=jdbc:postgresql://localhost:5432/promptdb-test
spring.datasource.username=${SPRING_DATASOURCE_USERNAME_TEST}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD_TEST}
spring.jpa.hibernate.ddl-auto=create-drop

admin.email=${ADMIN_EMAIL_TEST}
admin.password=${ADMIN_PASSWORD_TEST}

server.port=8082