spring.datasource.url=jdbc:postgresql://localhost:5432/promptdb-test
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:promptuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:promptpass}
spring.jpa.hibernate.ddl-auto=create-drop

admin.email=admin@example.com
admin.password=admin123