spring.application.name=promptengineering
spring.config.import=optional:file:.env[.properties]
#spring.config.import=secret.properties
spring.main.web-application-type=servlet

server.port=8080
#spring.web.resources.add-mappings=false
spring.mvc.favicon.enabled=false


server.servlet.session.timeout=3600000
server.servlet.session.cookie.max-age=2592000s


spring.freemarker.expose-spring-macro-helpers=true
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.freemarker.settings.default_encoding=UTF-8
#spring.freemarker.settings.auto_import=spring.ftl as spring



spring.main.lazy-initialization=true

spring.jpa.properties.hibernate.entity_manager_factory_interface=jakarta.persistence.EntityManagerFactory

app.max.encrypted.keys.length=10000
app.max.models.per.user=100
file.max-size=10485760
file.max-count=100
app.chat.page.max-size=100
app.message.page.max-size=100
app.message.max-total-size=10485760
rate.limit.max-requests=20
rate.limit.time-window-seconds=60

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB



#secret



gemini.api.key=${GEMINI_TESTING_API_KEY}

logging.level.org.springframework.security=${LOGGING_LEVEL}
logging.level.com.example.promptengineering=${LOGGING_LEVEL}

file.upload-dir=${UPLOAD_DIR}
media.upload-dir=${MEDIA_UPLOAD_DIR}

api.key.encryption.secret=${API_KEY_ENCRYPTION_SECRET}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile, email
spring.security.oauth2.client.registration.google.redirect-uri=${REDIRECT_GOOGLE_URL}
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.user-name-attribute=sub
spring.security.oauth2.client.registration.google.authorization-request-extra-parameters.access_type=offline


spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

app.domain=${APP_DOMAIN:localhost:8080}

server.ssl.enabled=false
security.require-ssl=false
server.forward-headers-strategy=framework

admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}




spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=*
spring.mail.properties.mail.smtp.localhost=mail.dominik-chyziak.pl
spring.mail.properties.mail.smtp.auth.mechanisms=LOGIN PLAIN
spring.mail.properties.mail.debug=true