package com.example.promptengineering.model;

public enum ActionType {
  LOGIN_SUCCESS, LOGIN_FAILURE, LOGOUT,
  PASSWORD_CHANGE, PASSWORD_RESET_REQUEST, PASSWORD_RESET_CONFIRM,
  TWOFA_VERIFY, TWOFA_ENABLE, TWOFA_DISABLE,
  ROLE_UPDATE, USER_CREATE, USER_DELETE,
  SHARED_KEY_GENERATE, SHARED_KEY_DELETE,
  BLOG_CREATE, BLOG_UPDATE, BLOG_DELETE,
  MEDIA_UPLOAD, MEDIA_DELETE,
  DATA_EXPORT, SENSITIVE_READ, ADMIN_ACTION,
  RATE_LIMIT_EXCEEDED
}